### ISSUE TITLE
Make landing page logo responsive

### ISSUE THREAD

**Issue by shreyaagrawal0809** [CivicDataLab/old-website#35]

**Comment by apoorv74** [comment]
@shreyaagrawal0809 are you working on this ?

**Comment by apoorv74** [comment]
hey @shreyaagrawal0809 are you working on this ?

**Comment by shreyaagrawal0809** [comment]
Not currently

**Comment by apoorv74** [comment]
Closing this for now then, will be taken care of during the website revamp
